#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jun 30, 2017 12:57:12 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import EarlyAlphaSim_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    EarlyAlphaSim_support.set_Tk_var()
    top = Simba_Frame (root)
    EarlyAlphaSim_support.init(root, top)
    root.mainloop()

w = None
def create_Simba_Frame(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    EarlyAlphaSim_support.set_Tk_var()
    top = Simba_Frame (w)
    EarlyAlphaSim_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Simba_Frame():
    global w
    w.destroy()
    w = None


class Simba_Frame:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1900x985+1+1")
        top.title("Simba Frame")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Scrolledlistbox1 = ScrolledListBox(top)
        self.Scrolledlistbox1.place(relx=0.77, rely=0.05, relheight=0.5
                , relwidth=0.22)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox1.configure(selectforeground="black")
        self.Scrolledlistbox1.configure(width=10)

        self.userinfoFrame = ttk.Labelframe(top)
        self.userinfoFrame.place(relx=0.01, rely=0.0, relheight=0.11
                , relwidth=0.17)
        self.userinfoFrame.configure(text='''User Information''')
        self.userinfoFrame.configure(width=330)

        self.UsernameEnt = ttk.Entry(self.userinfoFrame)
        self.UsernameEnt.place(relx=0.03, rely=0.57, relheight=0.25
                , relwidth=0.44)
        self.UsernameEnt.configure(textvariable=EarlyAlphaSim_support.usernameVar)
        self.UsernameEnt.configure(takefocus="")
        self.UsernameEnt.configure(cursor="ibeam")

        self.PasswordEnt = ttk.Entry(self.userinfoFrame)
        self.PasswordEnt.place(relx=0.52, rely=0.57, relheight=0.25
                , relwidth=0.44)
        self.PasswordEnt.configure(textvariable=EarlyAlphaSim_support.passwordVar)
        self.PasswordEnt.configure(takefocus="")
        self.PasswordEnt.configure(cursor="ibeam")

        self.userLab = ttk.Label(self.userinfoFrame)
        self.userLab.place(relx=0.03, rely=0.29, height=24, width=125)
        self.userLab.configure(background="#d9d9d9")
        self.userLab.configure(foreground="#000000")
        self.userLab.configure(relief=FLAT)
        self.userLab.configure(text='''Username''')

        self.passwordLab = ttk.Label(self.userinfoFrame)
        self.passwordLab.place(relx=0.52, rely=0.29, height=24, width=145)
        self.passwordLab.configure(background="#d9d9d9")
        self.passwordLab.configure(foreground="#000000")
        self.passwordLab.configure(relief=FLAT)
        self.passwordLab.configure(text='''Password''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.83, rely=0.01, height=26, width=232)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Data Operations List''')

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.optionsNB = ttk.Notebook(top)
        self.optionsNB.place(relx=0.01, rely=0.45, relheight=0.56, relwidth=0.27)

        self.optionsNB.configure(width=504)
        self.optionsNB.configure(takefocus="")
        self.optionsNB_t1 = ttk.Frame(self.optionsNB)
        self.optionsNB.add(self.optionsNB_t1, padding=3)
        self.optionsNB.tab(0, text="Time",underline="-1",)
        self.optionsNB_t2 = ttk.Frame(self.optionsNB)
        self.optionsNB.add(self.optionsNB_t2, padding=3)
        self.optionsNB.tab(1, text="Page 2",underline="-1",)
        self.optionsNB_t3 = ttk.Frame(self.optionsNB)
        self.optionsNB.add(self.optionsNB_t3, padding=3)
        self.optionsNB.tab(2, text="Page 3",underline="-1",)

        self.timeFrame1 = ttk.Labelframe(self.optionsNB_t1)
        self.timeFrame1.place(relx=0.0, rely=0.0, relheight=0.97, relwidth=0.98)
        self.timeFrame1.configure(text='''Optional Time Period''')
        self.timeFrame1.configure(width=490)

        self.starttimeEnt1 = ttk.Entry(self.timeFrame1)
        self.starttimeEnt1.place(relx=0.02, rely=0.1, relheight=0.05
                , relwidth=0.4)
        self.starttimeEnt1.configure(textvariable=EarlyAlphaSim_support.stdStartingTimeVar)
        self.starttimeEnt1.configure(takefocus="")
        self.starttimeEnt1.configure(cursor="ibeam")

        self.starttimeLab1 = ttk.Label(self.timeFrame1)
        self.starttimeLab1.place(relx=0.02, rely=0.04, height=24, width=249)
        self.starttimeLab1.configure(background="#d9d9d9")
        self.starttimeLab1.configure(foreground="#000000")
        self.starttimeLab1.configure(relief=FLAT)
        self.starttimeLab1.configure(text='''Starting Time (dd.mm.yyyy hh:mm:ss)''')

        self.endtimeLab1 = ttk.Label(self.timeFrame1)
        self.endtimeLab1.place(relx=0.02, rely=0.16, height=24, width=87)
        self.endtimeLab1.configure(background="#d9d9d9")
        self.endtimeLab1.configure(foreground="#000000")
        self.endtimeLab1.configure(relief=FLAT)
        self.endtimeLab1.configure(text='''Ending Time''')

        self.endtimeEnt1 = ttk.Entry(self.timeFrame1)
        self.endtimeEnt1.place(relx=0.02, rely=0.22, relheight=0.05
                , relwidth=0.4)
        self.endtimeEnt1.configure(textvariable=EarlyAlphaSim_support.stdEndingTimeVat)
        self.endtimeEnt1.configure(takefocus="")
        self.endtimeEnt1.configure(cursor="ibeam")

        self.timeButton1 = ttk.Button(self.timeFrame1)
        self.timeButton1.place(relx=0.08, rely=0.28, height=40, width=108)
        self.timeButton1.configure(command=EarlyAlphaSim_support.standardTime)
        self.timeButton1.configure(takefocus="")
        self.timeButton1.configure(text='''Use Standard''')

        self.epochstartENT = ttk.Entry(self.timeFrame1)
        self.epochstartENT.place(relx=0.55, rely=0.1, relheight=0.05
                , relwidth=0.4)
        self.epochstartENT.configure(textvariable=EarlyAlphaSim_support.epochStartingTimeVar)
        self.epochstartENT.configure(takefocus="")
        self.epochstartENT.configure(cursor="ibeam")

        self.epochstartLab = ttk.Label(self.timeFrame1)
        self.epochstartLab.place(relx=0.55, rely=0.04, height=24, width=148)
        self.epochstartLab.configure(background="#d9d9d9")
        self.epochstartLab.configure(foreground="#000000")
        self.epochstartLab.configure(relief=FLAT)
        self.epochstartLab.configure(text='''Starting Time (Epoch)''')

        self.TEntry1 = ttk.Entry(self.timeFrame1)
        self.TEntry1.place(relx=0.55, rely=0.22, relheight=0.05, relwidth=0.4)
        self.TEntry1.configure(textvariable=EarlyAlphaSim_support.epochEndingTimeVar)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.epochendLab = ttk.Label(self.timeFrame1)
        self.epochendLab.place(relx=0.55, rely=0.16, height=24, width=91)
        self.epochendLab.configure(background="#d9d9d9")
        self.epochendLab.configure(foreground="#000000")
        self.epochendLab.configure(relief=FLAT)
        self.epochendLab.configure(text='''Ending Time''')

        self.epochButton = ttk.Button(self.timeFrame1)
        self.epochButton.place(relx=0.65, rely=0.28, height=40, width=108)
        self.epochButton.configure(command=EarlyAlphaSim_support.epochTime)
        self.epochButton.configure(takefocus="")
        self.epochButton.configure(text='''Use Epoch''')

        self.showTimeButton = ttk.Button(self.timeFrame1)
        self.showTimeButton.place(relx=0.39, rely=0.28, height=40, width=98)
        self.showTimeButton.configure(command=EarlyAlphaSim_support.showRange)
        self.showTimeButton.configure(takefocus="")
        self.showTimeButton.configure(text='''Range''')

        self.lis37 = Listbox(top)
        self.lis37.place(relx=0.67, rely=0.05, relheight=0.18, relwidth=0.09)
        self.lis37.configure(background="white")
        self.lis37.configure(disabledforeground="#a3a3a3")
        self.lis37.configure(font="TkFixedFont")
        self.lis37.configure(foreground="#000000")
        self.lis37.configure(highlightbackground="#d9d9d9")
        self.lis37.configure(highlightcolor="black")
        self.lis37.configure(selectbackground="#c4c4c4")
        self.lis37.configure(selectforeground="black")
        self.lis37.configure(width=164)

        self.directInputFram = ttk.Labelframe(top)
        self.directInputFram.place(relx=0.18, rely=0.0, relheight=0.11
                , relwidth=0.17)
        self.directInputFram.configure(text='''Direct Input''')
        self.directInputFram.configure(width=330)

        self.inputDirectEnt = ttk.Entry(self.directInputFram)
        self.inputDirectEnt.place(relx=0.03, rely=0.57, relheight=0.25
                , relwidth=0.5)
        self.inputDirectEnt.configure(textvariable=EarlyAlphaSim_support.localFilePathVar)
        self.inputDirectEnt.configure(takefocus="")
        self.inputDirectEnt.configure(cursor="ibeam")

        self.fileInputPathLab = ttk.Label(self.directInputFram)
        self.fileInputPathLab.place(relx=0.03, rely=0.29, height=24, width=98)
        self.fileInputPathLab.configure(background="#d9d9d9")
        self.fileInputPathLab.configure(foreground="#000000")
        self.fileInputPathLab.configure(relief=FLAT)
        self.fileInputPathLab.configure(text='''File Input Path''')

        self.fileInputButton = ttk.Button(self.directInputFram)
        self.fileInputButton.place(relx=0.61, rely=0.57, height=30, width=98)
        self.fileInputButton.configure(command=EarlyAlphaSim_support.findLocalFilePath)
        self.fileInputButton.configure(takefocus="")
        self.fileInputButton.configure(text='''Browse''')

        self.outputLocFrame = ttk.Labelframe(top)
        self.outputLocFrame.place(relx=0.36, rely=0.0, relheight=0.11
                , relwidth=0.17)
        self.outputLocFrame.configure(text='''Output Location''')
        self.outputLocFrame.configure(width=330)

        self.localoutputpathEnt = ttk.Entry(self.outputLocFrame)
        self.localoutputpathEnt.place(relx=0.03, rely=0.57, relheight=0.25
                , relwidth=0.5)
        self.localoutputpathEnt.configure(textvariable=EarlyAlphaSim_support.localOutputPathVar)
        self.localoutputpathEnt.configure(takefocus="")
        self.localoutputpathEnt.configure(cursor="ibeam")

        self.localoutputpathLab = ttk.Label(self.outputLocFrame)
        self.localoutputpathLab.place(relx=0.03, rely=0.29, height=24, width=149)

        self.localoutputpathLab.configure(background="#d9d9d9")
        self.localoutputpathLab.configure(foreground="#000000")
        self.localoutputpathLab.configure(relief=FLAT)
        self.localoutputpathLab.configure(text='''Local Output File Path''')

        self.locOutputPathButton = ttk.Button(self.outputLocFrame)
        self.locOutputPathButton.place(relx=0.61, rely=0.57, height=30, width=98)

        self.locOutputPathButton.configure(command=EarlyAlphaSim_support.findLocalOutPath)
        self.locOutputPathButton.configure(takefocus="")
        self.locOutputPathButton.configure(text='''Browse''')

        self.cloudNB = ttk.Notebook(top)
        self.cloudNB.place(relx=0.01, rely=0.11, relheight=0.33, relwidth=0.2)
        self.cloudNB.configure(width=374)
        self.cloudNB.configure(takefocus="")
        self.cloudNB_t1 = ttk.Frame(self.cloudNB)
        self.cloudNB.add(self.cloudNB_t1, padding=3)
        self.cloudNB.tab(0, text="Cloud Input Location",underline="-1",)
        self.cloudNB_t2 = ttk.Frame(self.cloudNB)
        self.cloudNB.add(self.cloudNB_t2, padding=3)
        self.cloudNB.tab(1, text="Cloud Output Location",underline="-1",)

        self.projectselFrame1 = ttk.Labelframe(self.cloudNB_t1)
        self.projectselFrame1.place(relx=0.03, rely=0.0, relheight=0.98
                , relwidth=0.95)
        self.projectselFrame1.configure(text='''Project Selector''')
        self.projectselFrame1.configure(width=350)

        self.projectEnt1 = ttk.Entry(self.projectselFrame1)
        self.projectEnt1.place(relx=0.06, rely=0.18, relheight=0.09
                , relwidth=0.47)
        self.projectEnt1.configure(textvariable=EarlyAlphaSim_support.projectInputVar)
        self.projectEnt1.configure(takefocus="")
        self.projectEnt1.configure(cursor="ibeam")

        self.seriesEnt1 = ttk.Entry(self.projectselFrame1)
        self.seriesEnt1.place(relx=0.06, rely=0.39, relheight=0.09
                , relwidth=0.47)
        self.seriesEnt1.configure(textvariable=EarlyAlphaSim_support.seriesInputVar)
        self.seriesEnt1.configure(takefocus="")
        self.seriesEnt1.configure(cursor="ibeam")

        self.projectLab1 = ttk.Label(self.projectselFrame1)
        self.projectLab1.place(relx=0.06, rely=0.07, height=24, width=165)
        self.projectLab1.configure(background="#d9d9d9")
        self.projectLab1.configure(foreground="#000000")
        self.projectLab1.configure(relief=FLAT)
        self.projectLab1.configure(text='''Project''')

        self.seriesLab1 = ttk.Label(self.projectselFrame1)
        self.seriesLab1.place(relx=0.06, rely=0.28, height=24, width=155)
        self.seriesLab1.configure(background="#d9d9d9")
        self.seriesLab1.configure(foreground="#000000")
        self.seriesLab1.configure(relief=FLAT)
        self.seriesLab1.configure(text='''Series''')

        self.urlEnt1 = Entry(self.projectselFrame1)
        self.urlEnt1.place(relx=0.06, rely=0.6, relheight=0.08, relwidth=0.9)
        self.urlEnt1.configure(background="white")
        self.urlEnt1.configure(disabledforeground="#a3a3a3")
        self.urlEnt1.configure(font="TkFixedFont")
        self.urlEnt1.configure(foreground="#000000")
        self.urlEnt1.configure(highlightbackground="#d9d9d9")
        self.urlEnt1.configure(highlightcolor="black")
        self.urlEnt1.configure(insertbackground="black")
        self.urlEnt1.configure(selectbackground="#c4c4c4")
        self.urlEnt1.configure(selectforeground="black")
        self.urlEnt1.configure(textvariable=EarlyAlphaSim_support.urlInputVar)

        self.urlLab1 = Label(self.projectselFrame1)
        self.urlLab1.place(relx=0.06, rely=0.49, height=26, width=32)
        self.urlLab1.configure(activebackground="#f9f9f9")
        self.urlLab1.configure(activeforeground="black")
        self.urlLab1.configure(background="#d9d9d9")
        self.urlLab1.configure(disabledforeground="#a3a3a3")
        self.urlLab1.configure(foreground="#000000")
        self.urlLab1.configure(highlightbackground="#d9d9d9")
        self.urlLab1.configure(highlightcolor="black")
        self.urlLab1.configure(text='''URL''')

        self.dataButton1 = ttk.Button(self.projectselFrame1)
        self.dataButton1.place(relx=0.06, rely=0.7, height=30, width=98)
        self.dataButton1.configure(command=EarlyAlphaSim_support.getInputDataFromLogin)
        self.dataButton1.configure(takefocus="")
        self.dataButton1.configure(text='''Get Data''')

        self.projectselOutputFrame2 = ttk.Labelframe(self.cloudNB_t2)
        self.projectselOutputFrame2.place(relx=0.03, rely=0.03, relheight=0.95
                , relwidth=0.95)
        self.projectselOutputFrame2.configure(text='''Project Selector''')
        self.projectselOutputFrame2.configure(width=350)

        self.projectEnt2 = ttk.Entry(self.projectselOutputFrame2)
        self.projectEnt2.place(relx=0.06, rely=0.18, relheight=0.09
                , relwidth=0.47)
        self.projectEnt2.configure(textvariable=EarlyAlphaSim_support.cloudProjOutVar)
        self.projectEnt2.configure(takefocus="")
        self.projectEnt2.configure(cursor="ibeam")

        self.seriesEnt2 = ttk.Entry(self.projectselOutputFrame2)
        self.seriesEnt2.place(relx=0.06, rely=0.4, relheight=0.09, relwidth=0.47)

        self.seriesEnt2.configure(textvariable=EarlyAlphaSim_support.cloudOutSeriesVar)
        self.seriesEnt2.configure(takefocus="")
        self.seriesEnt2.configure(cursor="ibeam")

        self.projectLab2 = ttk.Label(self.projectselOutputFrame2)
        self.projectLab2.place(relx=0.06, rely=0.07, height=24, width=165)
        self.projectLab2.configure(background="#d9d9d9")
        self.projectLab2.configure(foreground="#000000")
        self.projectLab2.configure(relief=FLAT)
        self.projectLab2.configure(text='''Project''')

        self.seriesLab2 = ttk.Label(self.projectselOutputFrame2)
        self.seriesLab2.place(relx=0.06, rely=0.29, height=24, width=155)
        self.seriesLab2.configure(background="#d9d9d9")
        self.seriesLab2.configure(foreground="#000000")
        self.seriesLab2.configure(relief=FLAT)
        self.seriesLab2.configure(text='''Series''')

        self.urlEnt2 = Entry(self.projectselOutputFrame2)
        self.urlEnt2.place(relx=0.06, rely=0.62, relheight=0.09, relwidth=0.9)
        self.urlEnt2.configure(background="white")
        self.urlEnt2.configure(disabledforeground="#a3a3a3")
        self.urlEnt2.configure(font="TkFixedFont")
        self.urlEnt2.configure(foreground="#000000")
        self.urlEnt2.configure(highlightbackground="#d9d9d9")
        self.urlEnt2.configure(highlightcolor="black")
        self.urlEnt2.configure(insertbackground="black")
        self.urlEnt2.configure(selectbackground="#c4c4c4")
        self.urlEnt2.configure(selectforeground="black")
        self.urlEnt2.configure(textvariable=EarlyAlphaSim_support.cloudOutUrlVar)

        self.urlLab2 = Label(self.projectselOutputFrame2)
        self.urlLab2.place(relx=0.06, rely=0.51, height=26, width=32)
        self.urlLab2.configure(activebackground="#f9f9f9")
        self.urlLab2.configure(activeforeground="black")
        self.urlLab2.configure(background="#d9d9d9")
        self.urlLab2.configure(disabledforeground="#a3a3a3")
        self.urlLab2.configure(foreground="#000000")
        self.urlLab2.configure(highlightbackground="#d9d9d9")
        self.urlLab2.configure(highlightcolor="black")
        self.urlLab2.configure(text='''URL''')

        self.dataButton2 = ttk.Button(self.projectselOutputFrame2)
        self.dataButton2.place(relx=0.06, rely=0.73, height=30, width=98)
        self.dataButton2.configure(command=EarlyAlphaSim_support.pushDataSet)
        self.dataButton2.configure(takefocus="")
        self.dataButton2.configure(text='''Push Data''')

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(relx=0.69, rely=0.01, height=24, width=71)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Data Tags''')





# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()


